### ISSUE TITLE
How many Channel it can measure ?

### ISSUE THREAD

**Issue by asahajit** [MAWoodMain/PowerMonitorMK3#5]
How many channels it can measure?
Can we add WIFI.h Module for SSID and Password?
How it's performing in terms of accuracy?

**Comment by MAWoodMain** [comment]
> How many channels it can measure?
> Can we add WIFI.h Module for SSID and Password?
> How it's performing in terms of accuracy?

Hi, this version of the design is single channel (voltage, current and power)

The firmware is non functional, unfortunately I had trouble with the development and moved on before it became too much of a time sink

The accuracy in theory is largely down to the ade IC, most of the other system error you should be able to calibrate out
